version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: ./docker-files/Dockerfile
        tty: true
        #privileged: true    
        # image: frolvlad/alpine-python3
        volumes:
            - $PWD:/app/